apiVersion: v1
kind: Service
metadata:
  name: sample-service
  namespace: lab
spec:
  selector:
    app: sample-deployment
  type: NodePort
  ports:
  - protocol: TCP
    port: 8090
    nodePort: 30400
    targetPort: 8090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  namespace: lab
spec:
  selector:
    matchLabels:
      app: sample-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-deployment
    spec:
      containers:
      - name: sample
        image: lab/mysample:0.0.1
        imagePullPolicy: IfNotPresent
#        resources:
#          limits:
#            memory: "128Mi"
#            cpu: "500m"
        ports:
        - containerPort: 8090
        env:
        # spring boot env
        - name: SERVER_PORT
          value: "8090"
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: secret
              key: JWT_SECRET
