apiVersion: v1
kind: Service
metadata:
  name: sso-service
  namespace: lab
spec:
  selector:
    app: sso-deployment
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30300
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sso-deployment
  namespace: lab
spec:
  selector:
    matchLabels:
      app: sso-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: sso-deployment
    spec:
      containers:
      - name: sso
        image: lab/mysso:0.0.1
        imagePullPolicy: IfNotPresent
#        resources:
#          limits:
#            memory: "128Mi"
#            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        # spring boot env
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: secret
              key: JWT_SECRET
        # postgres env
        - name: POSTGRES_HOST
          value: postgres-service
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: config
              key: POSTGRES_URL
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: config
              key: POSTGRES_DB
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: POSTGRES_PASSWORD
