apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: lab
  annotations:
    kubernetes.io/service-account.name: ss
type: Opaque
data:
  POSTGRES_USERNAME: cm9vdA==   # root
  POSTGRES_PASSWORD: cm9vdA==   # root
  JWT_SECRET: aWFtaW5zZXVjcmVqd3RzZWNyZXQ=  # iaminseucrejwtsecret