apiVersion: v1
kind: Service
metadata:
  name: sso_service
  namespace: lab
spec:
  selector:
    app: sso_deployment
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sso_deployment
  namespace: lab
spec:
  selector:
    matchLabels:
      app: sso_deployment
  template:
    replica: 3

    metadata:
      labels:
        app: sso_deployment
    
    spec:
      containers:
      - name: sso
        image: 
        
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        
        ports:
        - containerPort: 8080
        
        env:
        # postgres env
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: secret
              key: POSTGRES_HOST
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: secret
              key: POSTGRES_DB
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: POSTGRES_PASSWORD
        # spring boot env
        - name: SPRING_BOOT_PORT
          value: "8080"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: secret
              key: JWT_SECRET
