apiVersion: v1
kind: Service
metadata:
  namespace: kube-logging
  name: kibana-service
spec:
  selector:
    app: kibana-deployment
  type: NodePort
  ports:
    - port: 8080
      targetPort: 5601
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-logging
  name: kibana-deployment
  labels:
    app: kibana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana-deployment
  template:
    metadata:
      labels:
        app: kibana-deployment
    spec:
      containers:
        - name: kibana-deployment
          image: docker.elastic.co/kibana/kibana:8.8.1
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 100m
          env:
            - name: ELASTICSEARCH_URL
              value: http://elasticsearch-service:9200
          ports:
            - containerPort: 5601