version: '3.8'

services:
    logstash:
        image: logstash:7.5.1
        container_name: logstash
        volumes:
            - ./logstash/:/usr/share/logstash/pipeline/
        depends_on:
            - elasticsearch
        links:
            - elasticsearch:es
        ports:
            - 4560:4560
      
    elasticsearch:
        image: elasticsearch:7.5.1
        container_name: elasticsearch
        environment:
            - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
            - "discovery.type=single-node" #以单一节点模式启动
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #设置使用jvm内存大小
#        volumes:
#            - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
#            - ./elasticsearch/data:/usr/share/elasticsearch/data #数据文件挂载
        ports:
            - 9200:9200
    kibana:
        image: kibana:7.5.1
        container_name: kibana
        depends_on:
            - elasticsearch
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch:9200
        ports:
            - 5601:5601